version: "3.9"

services:
  jupyter_module:
    build:
      context: . 
      dockerfile: Dockerfile
    restart: always 
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0
      --port=8888
      --no-browser
      --NotebookApp.toke=''
      --notebook-dir=/code
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "/code"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
